In [27]:
name = "Theerayut Khongsuk"
age = int(input("Enter your age: "))
print("Next year you will be", age+1, "years old.")
print(f"Hello, {name}! You are {age} years old.")

ValueError: invalid literal for int() with base 10: ''

In [ ]:
if ('0'):
    print('a')
else:
    print('b')

a


In [ ]:
age = int(input("Enter your age: "))
if age < 18:
    print("You are a minor.")
else:
    print("You are an adult.")

You are a minor.


In [ ]:
name = input("Enter your name: ")
namey = name.upper()
score = float(input("Enter your score: "))
if score >= 80:
    print(f"{namey}, you got an A.")
elif score >= 70 and score < 80:
    print(f"{namey}, you got a B.")
elif score >= 60 and score < 70:
    print(f"{namey}, you got a C.")
elif score >= 50 and score < 60:
    print(f"{namey}, you got a D.")
else:
    print(f"{namey}, you got an F.")    

THEERAYUT KHONGSUK, you got a D.


In [ ]:
password = int(input("Enter your password: "))
if password == 1234:
    print("Access granted.")
else:
    print("Access denied.")

Access denied.


In [ ]:
total_sum = 0

print("กรุณากรอกจำนวนเต็ม 5 จำนวน:")


for i in range(1, 6):

    num = int(input(f"จำนวนที่ {i}: "))
   
    total_sum += num

print("------------------------")
print(f"ผลรวมของตัวเลขทั้งหมดคือ: {total_sum}")

กรุณากรอกจำนวนเต็ม 5 จำนวน:
------------------------
ผลรวมของตัวเลขทั้งหมดคือ: 15


In [ ]:
for i in range(30):
    if i % 3 == 0:
        print(i, "Go")
    else:
        print(i, "No")

0 Go
1 No
2 No
3 Go
4 No
5 No
6 Go
7 No
8 No
9 Go
10 No
11 No
12 Go
13 No
14 No
15 Go
16 No
17 No
18 Go
19 No
20 No
21 Go
22 No
23 No
24 Go
25 No
26 No
27 Go
28 No
29 No


In [ ]:
age = int(input("Enter your age: "))
if age < 18:
    print("ยังเด็กอยู่")
else:
    print("โตแล้วนะ")

โตแล้วนะ


In [ ]:
score = float(input("enter your score: "))
if score >= 80:
    print("you got an A")
elif score >= 70 and score <80:
    print("you got a B")
elif score >= 60 and score <70:
    print("you got a C")
elif score >= 50 and score <60:
    print("you got a D")
else:
    print("you got a F")

you got a B


In [ ]:
total_sum = 0
print("กรอกจำนวนเต็ม 5 จำนวน: ")
for i in range(1, 6);
    num = int(input(f" "))

In [ ]:
a = int(input())
b = int(input())

while b != 0:
    temp = b
    b = a % b
    a = temp

print(a)


2


In [ ]:
N = int(input())

a, b = 0, 1
sum = 0
for i in range(N):
    next = a + b
    a = b
    b = next
    sum += a

print(sum)


4


In [ ]:
def function_name(parameters):

    result = parameters
    return result
answer = function_name("string")

In [ ]:
def consessions():
    print("Welcome to the concession stand!")
    print("We have the following items available:")
    print("1. Popcorn - $5")
    print("2. Soda - $3")
    print("3. Candy - $2")
    print("4. Nachos - $4")
    print("5. Hot Dog - $6")
consessions()

Welcome to the concession stand!
We have the following items available:
1. Popcorn - $5
2. Soda - $3
3. Candy - $2
4. Nachos - $4
5. Hot Dog - $6


In [ ]:
def greet(name):
    return(f"Hello, {name}!")
greet ("Sea")

'Hello, Sea!'

In [ ]:
def calculation1(a, b):
    z = a + b
    return z
def calculation2(a, b):
    z = calculation1(a, b)
    return z
print(calculation2(1, 2))

3


In [ ]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

In [ ]:
def local_example():
    x = 10  # This variable is local to the function
    print("Inside the function, x =", x)

In [ ]:
"""texttools.py"""

def count_consonants(text):
    vowels = "aeiouAEIOU"
    count = 0
    for char in text:
        if char.isalpha() and char not in vowels:
            count += 1
    return count

def reverse_text(text):
    return text[::-1]

text = input("Enter text: ")

print("consonants =", count_consonants(text))
print("Reverse =", reverse_text(text))

consonants = 0
Reverse = uoiea


In [ ]:
# main.py
import texttools

# ข้อความตัวอย่างสำหรับทดสอบ
message = "Hello World"

print(f"ข้อความดั้งเดิม: '{message}'")
print("-" * 35

# 1. ทดสอบนับพยัญชนะ
consonant_count = texttools.count_consonants(message)
print(f"จำนวนพยัญชนะ: {consonant_count} ตัว")


# 2. ทดสอบข้อความกลับด้าน
reversed_msg = texttools.reverse_text(message)
print(f"ข้อความกลับด้าน: '{reversed_msg}'")

ข้อความดั้งเดิม: 'Hello World'
-----------------------------------
จำนวนพยัญชนะ: 7 ตัว
ข้อความกลับด้าน: 'dlroW olleH'


In [ ]:
# Given lists
list1 = [1, 2, 3]
list2 = [3, 4, 5]

# Concatenate lists
for i in range(len(list1)):
    if list1[i] == list2[0]:
        concatenated_list = list1 + list2[1:]
        break
    elif list1[i] == list2[-1]:
        concatenated_list = list1 + list2[:-1]
        break
    elif list1[0] == list2[i]:
        concatenated_list = list1[1:] + list2
        break
else:
    concatenated_list = list1 + list2
print("Concatenated list:", concatenated_list)




Concatenated list: [1, 2, 3, 4, 5]


In [ ]:
text = input("Enter a sentence: ")
    modified_text = len(text)
    print("your sentence is :", modified_text)

IndentationError: unexpected indent (200570786.py, line 3)

In [ ]:
import matplotlib.pyplot as plt
# Sample data
x = [1, 2, 3, 4, 5]
y = [10, 20, 25, 30, 35]
# Create line plot
plt.plot(x, y)
# Show the plot
plt.show()

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
try:
    num = int(input("Enter a number: "))
    result = 10 / num
    print(result)
except ValueError:
    print("Not a valid number.")
except ZeroDivisionError:
    print("Cannot divide by zero.")
finally:
    print("Done")

Not a valid number.
Done


In [ ]:
items = [1, 2, 3]
try:
    i = int(input("Pick index 0-2: "))
    print("You chose:", items[i])
except (ValueError, IndexError) as e:
    print("Invalid choice:", e, "Please pick a valid index between 0 and 2.")

Invalid choice: list index out of range Please pick a valid index between 0 and 2.


In [ ]:
registered_users = ["Alice", "john"]

username = str(input("Enter your username: "))
password = int(input("Enter your password: "))

try:
    if username in registered_users:
        raise ValueError("This username is already registered.")
    if len(str(password)) < 6:
        raise ValueError("Your password is too short. Please enter a password with at least 6 characters.")
    print("Your username is :", username)
    print("Your password is :", password)

except ValueError as error_message:
    print(error_message)


Your password is : 123456
Your username is : Sea


In [ ]:
with open("a.txt", "w") as f:
    f.write("hi\n")
with open("a.txt") as f:
    print(f.read())

hi



In [ ]:
with open("n.txt", "w") as f:
    for i in range(1, 6):
        f.write(f"{i}\n")
total = sum(int(line) for line in open("n.txt"))
print(total)

15


In [ ]:
with open("a.txt", "w") as f:
    f.write("one\n")
with open("a.txt", "a") as f:
    f.write("two\n")
print(open("a.txt").read())

one
two



In [ ]:
with open('hi.txt', 'w') as f:
    f.write('Hello, file!\n')

with open('hi.txt', 'r') as f:
    print(f.read())

Hello, file!



In [ ]:
with open('notes.txt', 'w') as f:
    f.write('first line\n')
    f.writelines(['second\n', 'third\n'])

with open('notes.txt', 'r') as f:
    print(f.read())

import os
print('files here:', [x for x in os.listdir('.') if x.endswith('.txt')])

first line
second
third

files here: ['hi.txt', 'notes.txt', 'n.txt', 'a.txt']


In [ ]:
with open('log.txt', 'w') as f:
    f.write('line 1\n')

with open('log.txt', 'a') as f:
    f.write('line 2\n')

with open('log.txt', 'r') as f:
    print(f.read())

line 1
line 2



In [ ]:
import json
d = {"x": 1, "y": [2, 3]}
s = json.dumps(d)
print(s)
print(json.loads(s)["y"])

{"x": 1, "y": [2, 3]}
[2, 3]


In [ ]:
import csv
with open("d.csv", "w", newline="") as f:
    csv.writer(f).writerows([["a", "b"], [1, 2]])
with open("d.csv") as f:
    print(list(csv.reader(f)))

[['a', 'b'], ['1', '2']]


In [ ]:
import json
d = {"users": [{"n": "A"}, {"n": "B"}]}
print(json.dumps(d, indent=2))

{
  "users": [
    {
      "n": "A"
    },
    {
      "n": "B"
    }
  ]
}


In [ ]:
import json
data = {'name': 'Alice', 'age': 30, 'skills': ['py', 'sql']}
with open('data.json', 'w') as f:
    json.dump(data, f)

with open('data.json', 'r') as f:
    print(json.load(f))

{'name': 'Alice', 'age': 30, 'skills': ['py', 'sql']}


In [ ]:
import csv
with open('data.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['Name', 'Age', 'City'])
    w.writerow(['Alice', 30, 'New York'])
    w.writerow(['Bob', 25, 'San Francisco'])

with open('data.csv', 'r') as f:
    for row in csv.reader(f):
        print(row)

['Name', 'Age', 'City']
['Alice', '18', 'New York']
['Bob', '19', 'San Francisco']


In [ ]:
import csv
with open('data.csv', 'w', newline='') as f:
    w = csv.writer(f)
    w.writerow(['Name', 'Age'])
    w.writerow(['Alice', 30])
    w.writerow(['Bob', 25])

with open('data.csv', 'r') as f:
    for row in csv.DictReader(f):
        print(dict(row))

{'Name': 'Alice', 'Age': '30'}
{'Name': 'Bob', 'Age': '25'}


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a * 10)

[10 20 30 40]


In [43]:
import numpy as np
m = np.array([[1, 2], [3, 4]])
print(m.sum(), m.sum(axis=0))

10 [4 6]


In [39]:
import numpy as np
a = np.arange(1, 6)
print(a, a.sum(), a.mean())

[1 2 3 4 5] 15 3.0


In [40]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * 2)

[5 7 9]
[2 4 6]


In [41]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", a.shape)
print("a[1,2]:", a[1, 2])
print("row sums:", a.sum(axis=1))
print("max:", a.max())

shape: (2, 3)
a[1,2]: 6
row sums: [ 6 15]
max: 6


In [45]:
import numpy as np
m = np.zeros((4, 4))
for i in range(4):
    m[i, i] = 1
print(m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
with open("num.txt", "w") as f:
    for i in range(1, 11):
        f.write(f"{i}\n")
total = sum(int(line) for line in open("num.txt"))
print(total)

55


In [70]:
import numpy as np
m = np.zeros((4, 4))
for i in range(4):
    m[i, i] = 1
print(m)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
