Question 1-1

In [2]:
with open('sample.txt', 'r') as file:
    content = file.read()
    print(content)


Hello, this is a sample text file.
It contains multiple lines.
This is the third line.



Question 1-2

In [3]:
with open('output.txt', 'w') as file:
    file.write('This is the first line.\n')
    file.write('This is the second line.\n')
    print('File created successful')


File created successful


Question 1-3

In [4]:
with open('output.txt', 'r') as file:
    content = file.read()
    print(content)


This is the first line.
This is the second line.



Question 1-4

In [5]:
with open('output.txt', 'a') as file:
    file.write('This is the appended line.\n')
    print('New line is appended')


New line is appended


Question 1-5

In [6]:
with open('output.txt', 'r') as file:
    content = file.read()
    print(content)


This is the first line.
This is the second line.
This is the appended line.



Question 2-1

In [2]:
import pandas as pd

df = pd.read_csv('data.csv')
print(df)

      Name  Age         City
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago


Question 2-2

In [17]:
data = {
    'Product': ['Pen', 'Notebook', 'Eraser'],
    'Price': [1.2, 2.5, 0.5],
    'Quantity': [100, 200, 300]
}

df = pd.DataFrame(data)
df.to_csv('inventory.csv', index=False)

In [18]:
data = {
    'Product': ['Pen', 'Notebook', 'Eraser'],
    'Price': [1.2, 2.5, 0.5],
    'Quantity': [100, 200, 300]
}

df = pd.DataFrame(data)
df.to_csv('inventory.csv', index=False)
print(df)


    Product  Price  Quantity
0       Pen    1.2       100
1  Notebook    2.5       200
2    Eraser    0.5       300


Question 2-3

In [42]:
import pandas as pd

df = pd.read_csv('data.csv')
average_age = df['Age'].mean()
print(f'The average age is {average_age:.2f} years.')
oldest_person = df.loc[df['Age'].idxmax()]
print(f'The oldest person is {oldest_person["Name"]} from {oldest_person["City"]}, aged {oldest_person["Age"]}.')


The average age is 30.00 years.
The oldest person is Charlie from Chicago, aged 35.


Question 3-1

In [43]:
import numpy as np

data = np.loadtxt('numbers.txt')
print(data

SyntaxError: unexpected EOF while parsing (4271575009.py, line 4)

In [47]:
import numpy as np

data = np.loadtxt('numbers.txt')
print(data)

[[1.5 2.3 3.1]
 [4.  5.2 6.8]
 [7.9 8.4 9. ]]


Question 3-2

In [49]:
import numpy as np

data = np.array([[1.5, 2.3, 3.1],
                 [4.0, 5.2, 6.8],
                 [7.9, 8.4, 9.0]])

np.savetxt('array_data.txt', data, fmt='%.2f', delimiter=',')
loaded_data = np.loadtxt('array_data.txt', delimiter=',')
print(loaded_data)


[[1.5 2.3 3.1]
 [4.  5.2 6.8]
 [7.9 8.4 9. ]]


Question 3-3

In [6]:
import numpy as np

data = np.genfromtxt('data_with_missing.txt', delimiter=',', filling_values=np.nan)

col_means = np.nanmean(data, axis=0)
inds = np.where(np.isnan(data))
data[inds] = np.take(col_means, inds[1])
print(data)


[[1.  2.  3. ]
 [4.  5.  6. ]
 [7.  8.  4.5]]


Question 4-1

In [19]:
import pandas as pd

df = pd.read_csv('employee_data.csv')
df['Bonus'] = df['Salary'] * 0.10
df.to_csv('employee_data_with_bonus.csv', index=False)

In [20]:
import pandas as pd

df = pd.read_csv('employee_data.csv')
df['Bonus'] = df['Salary'] * 0.10
df.to_csv('employee_data_with_bonus.csv', index=False)
print(df)

          Name   Department  Salary   Bonus
0     John Doe  Engineering   75000  7500.0
1   Jane Smith    Marketing   65000  6500.0
2  Emily Davis        Sales   70000  7000.0


Question 4-2

In [21]:
import pandas as pd
import numpy as np

data = {
    'EmployeeID': [1, 3, 2, 4, np.nan],
    'Name': ['John Doe', 'Emily Davis', 'Jane, 'Michael, np.nan],
    'DepartmentID': [101, 101, 102, 103, 104],
    'DepartmentName': [Eng, Eng, 'Marketing', 'Sales', 'HR']
}
merged_right = pd.DataFrame(data)

print("Before Handling Missing Data:")
print(merged_right)

missing_data = merged_right[merged_right['EmployeeID'].isna() | merged_right['Name'].isna()]
print("\nRows with Missing Data:")
print(missing_data)


SyntaxError: invalid syntax (1224977282.py, line 6)

In [23]:
import pandas as pd
import numpy as np

data = {
    'EmployeeID': [1, 3, 2, 4, np.nan],
    'Name': ['John Doe', 'Emily Davis', 'Jane Smith', 'Michael Brown', np.nan],
    'DepartmentID': [101, 101, 102, 103, 104],
    'DepartmentName': ['Engineering', 'Engineering', 'Marketing', 'Sales', 'HR']
}
merged_right = pd.DataFrame(data)

print("Before Handling Missing Data:")
print(merged_right)

missing_data = merged_right[merged_right['EmployeeID'].isna() | merged_right['Name'].isna()]
print("\nRows with Missing Data:")
print(missing_data)


Before Handling Missing Data:
   EmployeeID           Name  DepartmentID DepartmentName
0         1.0       John Doe           101    Engineering
1         3.0    Emily Davis           101    Engineering
2         2.0     Jane Smith           102      Marketing
3         4.0  Michael Brown           103          Sales
4         NaN            NaN           104             HR

Rows with Missing Data:
   EmployeeID Name  DepartmentID DepartmentName
4         NaN  NaN           104             HR


Question 4-3

In [24]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 45, 28],
    'Gender': ['F', 'M', 'M', 'M'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer']
}
df = pd.DataFrame(data)

selected_columns = df[['Name', 'Occupation']]
print("Selected Columns:")
print(selected_columns)

filtered_rows = df[df['Age'] > 30]
print("\nFiltered Rows (Age > 30):")
print(filtered_rows)


Selected Columns:
      Name Occupation
0    Alice   Engineer
1      Bob     Doctor
2  Charlie     Artist
3    David     Lawyer

Filtered Rows (Age > 30):
      Name  Age Gender Occupation
1      Bob   32      M     Doctor
2  Charlie   45      M     Artist


Question 4-4

In [25]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 45, 28],
    'Gender': ['F', 'M', 'M', 'M'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer']
}
df = pd.DataFrame(data)

# Group by 'Gender' and calculate the average 'Age'
group_by_gender = df.groupby('Gender')['Age'].mean().reset_index()
print(group_by_gender)


  Gender   Age
0      F  25.0
1      M  35.0


Question 4-5

In [26]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 32, 45]
})

df2 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'David'],
    'City': ['New York', 'Los Angeles', 'Chicago']
})

merged_df = pd.merge(df1, df2, on='Name', how='inner')
print(merged_df)


    Name  Age         City
0  Alice   25     New York
1    Bob   32  Los Angeles


Question 4-6

In [27]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 45, 28],
    'Gender': ['F', 'M', 'M', 'M'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer']
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)

charlie_row = df.loc['Charlie']
print("Row for Charlie:")
print(charlie_row)

selected_data = df.loc[['Alice', 'Bob'], ['Age', 'Occupation']]
print("\nSelected data for Alice and Bob:")
print(selected_data)


Row for Charlie:
Age               45
Gender             M
Occupation    Artist
Name: Charlie, dtype: object

Selected data for Alice and Bob:
       Age Occupation
Name                 
Alice   25   Engineer
Bob     32     Doctor


Question 4-7

In [28]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 32, 45, 28],
    'Gender': ['F', 'M', 'M', 'M'],
    'Occupation': ['Engineer', 'Doctor', 'Artist', 'Lawyer']
}
df = pd.DataFrame(data)
df.set_index('Name', inplace=True)

df.loc['David', 'Occupation'] = 'Data Scientist'
df.loc['Bob', 'Age'] += 3
print("Updated DataFrame:")
print(df)


Updated DataFrame:
         Age Gender      Occupation
Name                               
Alice     25      F        Engineer
Bob       35      M          Doctor
Charlie   45      M          Artist
David     28      M  Data Scientist


Question 4-8

In [29]:
import pandas as pd

# Sample DataFrame
data = {
    'First Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 28, 30],
    'Location': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

df['Salary'] = [70000, 80000, 75000]
print(df)


  First Name  Age     Location  Salary
0      Alice   25     New York   70000
1        Bob   28  Los Angeles   80000
2    Charlie   30      Chicago   75000


Question 4-9

In [31]:
import pandas as pd

data = {
    'First Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 28, 30],
    'Location': ['New York', 'Los Angeles', 'Chicago'],
    'Salary': [70000, 80000, 75000]
}
df = pd.DataFrame(data)

df.loc[df['Age'] > 27, 'Salary'] += 5000
print(df)


  First Name  Age     Location  Salary
0      Alice   25     New York   70000
1        Bob   28  Los Angeles   85000
2    Charlie   30      Chicago   80000


Question 4-10

In [32]:
import pandas as pd

# Sample DataFrame
data = {
    'First Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 28, 30],
    'Location': ['New York', 'Los Angeles', 'Chicago'],
    'Salary': [70000, 85000, 80000]
}

df = pd.DataFrame(data)
df = df[df['First Name'] != 'Charlie']
print(df)


  First Name  Age     Location  Salary
0      Alice   25     New York   70000
1        Bob   28  Los Angeles   85000
